- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - release-notes-jobs
      - lib-forward-testing
    post:
      jobs:
        - openstack-tox-cover
